### ISSUE TITLE
Warning in 2024.6

### ISSUE THREAD

**Issue by ildar170975** [twrecked/hass-virtual#103]
2024-06-10 21:38:52.156 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'virtual' at custom_components/virtual/device_tracker.py, line 64: with open(STATE_FILE, 'r') as f: (offender: /config/custom_components/virtual/device_tracker.py, line 64: with open(STATE_FILE, 'r') as f:), please create a bug report at https://github.com/twrecked/hass-virtual/issues
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
sys.exit(main())
File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
exit_code = runner.run(runtime_conf)
File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
return loop.run_until_complete(setup_and_run_hass(runtime_config))
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
self.run_forever()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
self._run_once()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once
handle._run()
File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 261, in _async_setup_integration
create_eager_task(legacy_platform.async_setup_legacy(hass, tracker))
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task
return Task(coro, loop=loop, name=name, eager_start=True)
File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 341, in async_setup_legacy
setup = await self.platform.async_setup_scanner(
File "/config/custom_components/virtual/device_tracker.py", line 64, in async_setup_scanner
with open(STATE_FILE, 'r') as f:

**Comment by Tony763** [comment]
Hi @ildar170975, try to update version of hass-Virtual. Latest version do not contain blocking call `open`.

**Comment by ildar170975** [comment]
Hi, thanks for a suggestion!
I intentionally do not install 0.9 since it is still marked "alpha".

**Comment by Tony763** [comment]
I think that 0.9 is quite stable and safe to use. I personally use it for last 3 months.

**Comment by twrecked** [comment]
As for 'alpha', that's just me being distracted. I'll move it up to beta some time this week.

**Comment by ildar170975** [comment]
Guys, thanks a lot!
Will try 0.9.
Will close the issue then.

**Comment by leen67** [comment]
I just updated from 0.8 to version 0.9.0a9 but still getting these errors above on HA 2024.6.2.

**Comment by Tony763** [comment]
Hi @leen67 could You post an exact  error mesage, please?

**Comment by leen67** [comment]
Sure! Here are the errors in home-assistant.log :
2024-06-15 12:15:35.128 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'virtual' at custom_components/virtual/cfg.py, line 69: with open(default_meta_file(hass), 'r') as meta_file: (offender: /config/custom_components/virtual/cfg.py, line 69: with open(default_meta_file(hass), 'r') as meta_file:), please create a bug report at https://github.com/twrecked/hass-virtual/issues
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component
    result = await _async_setup_component(hass, domain, config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 447, in _async_setup_component
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 449, in <genexpr>
    create_eager_task(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/virtual/__init__.py", line 116, in async_setup_entry
    vcfg.load()
  File "/config/custom_components/virtual/cfg.py", line 279, in load
    meta_data = self._load_meta_data()
  File "/config/custom_components/virtual/cfg.py", line 269, in _load_meta_data
    return _load_meta_data(self._hass, self._group_name)
  File "/config/custom_components/virtual/cfg.py", line 69, in _load_meta_data
    with open(default_meta_file(hass), 'r') as meta_file:

2024-06-15 12:15:35.141 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'virtual' at custom_components/virtual/cfg.py, line 149: entities = load_yaml(file_name).get(ATTR_DEVICES, []) (offender: /usr/src/homeassistant/homeassistant/util/yaml/loader.py, line 226: with open(fname, encoding="utf-8") as conf_file:), please create a bug report at https://github.com/twrecked/hass-virtual/issues
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component
    result = await _async_setup_component(hass, domain, config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 447, in _async_setup_component
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 449, in <genexpr>
    create_eager_task(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/virtual/__init__.py", line 116, in async_setup_entry
    vcfg.load()
  File "/config/custom_components/virtual/cfg.py", line 280, in load
    devices = self._load_user_data()
  File "/config/custom_components/virtual/cfg.py", line 276, in _load_user_data
    return _load_user_data(self._file_name)
  File "/config/custom_components/virtual/cfg.py", line 149, in _load_user_data
    entities = load_yaml(file_name).get(ATTR_DEVICES, [])

**Comment by twrecked** [comment]
Happening to me. I'll need to figure out the fix.

**Comment by Tony763** [comment]
Yep, this is different error from above. 'cfg.py' contain blocking call. Converting these functions to async varsion should fix that. Using async with aiofiles.open( would not yield error.

**Comment by twrecked** [comment]
@Tony763 thanks for the pointer... `aiofiles` seems to work. I'll investigate some more and I'll aim for a fix later on.

**Comment by twrecked** [comment]
It should be fixed by 0.9.0b10, can you give it a try.

**Comment by leen67** [comment]
The warnings are gone with 0.9.0b10. Thanks a lot guys!

**Comment by twrecked** [comment]
Good to hear.
