### ISSUE TITLE
Cover: adding several devices causes an error if yaml-anchor is used

### ISSUE THREAD

**Issue by ildar170975** [twrecked/hass-virtual#128]
Consider this code:
```
version: 1
devices:
  Test Cover:
    - platform: cover
      initial_value: 'closed'
      open_close_duration: 5
      open_close_tick: 1

  Test Cover abc:
    - platform: cover
      initial_value: 'closed'
      open_close_duration: 5
      open_close_tick: 1
```
Trying to add these covers:
![изображение](https://github.com/user-attachments/assets/297c38e0-4afc-4409-8b4d-243a128f6969)

Seems that 2 covers are created properly:
![изображение](https://github.com/user-attachments/assets/fbd58020-8a9b-4a5d-861b-21518f7cf7b0)

And no errors/warnings in Log.

The consider this code:
```
version: 1
devices:
  Test Cover: &ref_settings
    - platform: cover
      initial_value: 'closed'
      open_close_duration: 5
      open_close_tick: 1

  Test Cover abc: *ref_settings
```
which is supposed to produce same result.
But it gives an error:
![изображение](https://github.com/user-attachments/assets/e99335cc-768b-43a8-9752-da7fc607bfdd)

No covers are created.

There is an error in Log:
2024-08-23 19:36:40.903 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry imported - virtual for virtual
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/virtual/__init__.py", line 149, in async_setup_entry
await vcfg.async_load()
File "/config/custom_components/virtual/cfg.py", line 306, in async_load
platform = entity.pop(CONF_PLATFORM)
^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'platform'

**Comment by ildar170975** [comment]
Mysteriously this variant works:
```
version: 1
devices:
  Test Cover:
    - <<: &ref_settings
        platform: cover
        initial_value: 'closed'
        open_close_duration: 5
        open_close_tick: 1

  Test Cover abc:
    - *ref_settings
```
