### ISSUE TITLE
[FR] add a "valve" entity

### ISSUE THREAD

**Issue by ildar170975** [twrecked/hass-virtual#91]
Please add a virtual "valve" entity introduced in 2024.1.

**Comment by Tony763** [comment]
Doc: https://www.home-assistant.io/integrations/valve/
Src: https://github.com/home-assistant/core/tree/dev/homeassistant/components/valve

**Comment by twrecked** [comment]
Bit late sorry, but I just added valve to 0.9.0b13.

**Comment by Tony763** [comment]
Will test it in the morning, thanks :)

**Comment by Tony763** [comment]
Setting availability state works correctly, but turning valve ON threw error.

```
  Test Valve:
  - platform: valve
    initial_value: 'closed'
    open_close_duration: 10
    open_close_tick: 1
    initial_availability: false
```

```
024-08-16 19:59:45.744 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [134347817255408] Unexpected exception
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
response = await hass.services.async_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2763, in async_call
response_data = await coro
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2806, in _execute_service
return await target(service_call)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 999, in entity_service_call
single_response = await _handle_entity_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1071, in _handle_entity_call
result = await task
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/valve/__init__.py", line 264, in async_set_valve_position
await self.hass.async_add_executor_job(self.set_valve_position, position)
File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/virtual/valve.py", line 95, in set_valve_position
self._set_position(position)
File "/config/custom_components/virtual/entity.py", line 199, in _set_position
self._tick()
File "/config/custom_components/virtual/entity.py", line 227, in _tick
async_call_later(self.hass, self._open_close_tick, self._update_position)
File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1590, in async_call_later
return loop.call_at(loop.time() + delay, _run_async_call_action, hass, job).cancel
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 776, in call_at
self._check_thread()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 834, in _check_thread
raise RuntimeError(
RuntimeError: Non-thread-safe operation invoked on an event loop other than the current one
```

**Comment by twrecked** [comment]
That was done through a service call?

**Comment by Tony763** [comment]
Availability trough service call in developer tools. Turning ON by card in lovelance.

**Comment by twrecked** [comment]
Both those are working here. Odd. I'll take a look.

**Comment by twrecked** [comment]
Which home assistant version are you using?

**Comment by Tony763** [comment]
2024.8.1 in Docker 
Should be always latest when available, it updated automatically by WatchTower

**Comment by twrecked** [comment]
I'm running exactly the same version. Can I ask which type of lovelace card?

**Comment by Tony763** [comment]
Default one:

![image](https://github.com/user-attachments/assets/5c31cf00-e258-4e11-bb7d-572e6bd11317)

It occur on each action I do.

**Comment by Tony763** [comment]
Running 2024.8.2, watch tower just finished update.  Behavior is same.

**Comment by twrecked** [comment]
I think it's because I don't have asyncio debug enabled. I'm just figuring out how to turn that on.

**Comment by Tony763** [comment]
Maybe `loop.set_debug()` would help.
https://docs.python.org/3/library/asyncio-dev.html

**Comment by twrecked** [comment]
I used the profiler. I reproduced it so I'll fix it.

**Comment by twrecked** [comment]
Should fixed in b15; turned out I'd misunderstood the async stuff. The code is actually cleaner now.

**Comment by Tony763** [comment]
Ah, I looked into PR and think You just forgot to covert these into asynchronous :slightly_smiling_face:  B15 fixes it completely for me. Thanks

**Comment by ildar170975** [comment]
Guys, thanks a lot for adding valves.
Tested in b15.
Config:
```
version: 1
devices:
  Test Valve:
  - platform: valve
    initial_value: 'closed'
    open_close_duration: 5
    open_close_tick: 1
```
This is my 1st experience with `valve` entities, so may be I am making obvious mistakes.
Tried to use this service call:
```
      perform_action: valve.set_valve_position
      target:
        entity_id: valve.test_valve
      data:
        position: 33
```
And the final point is "40":
![изображение](https://github.com/user-attachments/assets/554772db-6f6b-44b6-972a-fe4a4c3e5d10)

Is it expected?

**Comment by ildar170975** [comment]
BTW, in docs it is written:
![изображение](https://github.com/user-attachments/assets/7c7a3558-81b6-4438-ba98-63afdbed91b8)

but in fact services are called differently:
![изображение](https://github.com/user-attachments/assets/db5eaac6-0248-4ef3-926d-54a3e32b0151)

and this difference comes from official [Docs](https://www.home-assistant.io/integrations/valve/):
![изображение](https://github.com/user-attachments/assets/aca269b2-a8ee-4c29-afdc-1d52525d4e8a)

Prepared an issue about this error in Docs - https://github.com/home-assistant/home-assistant.io/issues/34407
