### ISSUE TITLE
0.9.x - Cannot setup

### ISSUE THREAD

**Issue by Tony763** [twrecked/hass-virtual#94]
Hi @twrecked, just started to try new 0.9.x version (current master). Following error occurred immediately at begging.
Configuration is from pre-0.8.x version.
Hass version 2024.1.5

```
Traceback (most recent call last):
  File "/srv/ha/venv/lib/python3.11/site-packages/homeassistant/setup.py", line 332, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/virtual/__init__.py", line 68, in setup
    hass.async_create_task(
  File "/srv/ha/venv/lib/python3.11/site-packages/homeassistant/core.py", line 624, in async_create_task
    task = self.loop.create_task(target, name=name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 436, in create_task
    task = tasks.Task(coro, loop=self, name=name, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 763, in call_soon
    self._check_thread()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 800, in _check_thread
    raise RuntimeError(
RuntimeError: Non-thread-safe operation invoked on an event loop other than the current one
```

**Comment by Tony763** [comment]
Changing `def setup(...` to `async def async_setup(....` allow integration to start without error. But no configuration from `configuration.yaml` is added. HA only complain about non supported configuration entries in platforms (light, switch,..)

**Comment by twrecked** [comment]
Was this seen on an upgrade?

**Comment by Tony763** [comment]
Yes.
Note: I use it as cloned repository so upgrade was done by `git pull` and ha restart.

**Comment by twrecked** [comment]
Thanks for the confirmation. I'll look into this.

The 'def setup' call is just used to trigger the upgrade, subsequent starts will not get to the `async_create_task` code which is why I'm not seeing it here. I'll revert here and fix it.

It also explains why none of your config made it in the upgrade.

**Comment by twrecked** [comment]
I just merged in your fix.

If you didn't delete your old config and you want to try the upgrade again you should be able to:

- delete the _Virtual_ integration from `Settings -> Integrations`
- checkout and copy the 0.7 branch into `custom_components` and restart _HA_
- checkout and copy the master branch into `custom_components` and restart _HA_

**Comment by Tony763** [comment]
Just tried. Integration starts, but `virtual.yaml` was not created and no components were moved.

**Comment by twrecked** [comment]
I'll give it a go here.

**Comment by twrecked** [comment]
It worked here for me. Assuming you currently have the latest virtual component installed, these are the steps I took:

- I reverted back to old version of the code, I manually deleted the old `custom_components/virtual` directory and copied over the previous version but _HACS_ should work as well
- I deleted the _Virtual_ integration from the `Settings -> Integration` page
- I stopped the _Home Assistant_ instance running
- I deleted the new data files; these are `virtual.yaml` and `.storage/virtual.meta.json`
- I installed the new version of the code, I manually deleted the old `custom_components/virtual` directory and copied over the new version but _HACS_ should work as well
- I restarted the _Home Assistant_ instance.

And `virtual.yaml` was created.

I recommend turning on debug for the virtual component before doing this, that way you can poke around in the logs and make sure it's doing the work we expect it to.

```yaml
logger:
  default: info
  logs:
    custom_components.virtual: debug
```

You should see lines like this appearing in the log:

```
2024-02-03 15:02:16.367 DEBUG (MainThread) [custom_components.virtual] importing a YAML setup
 ..
2024-02-03 15:02:16.396 INFO (MainThread) [custom_components.virtual.cfg] devices={..your devices here...}]}
2024-02-03 15:02:16.396 DEBUG (MainThread) [custom_components.virtual.cfg] uid=steve_presence
2024-02-03 15:02:16.396 DEBUG (MainThread) [custom_components.virtual.cfg] eid=binary_sensor.virtual_steve_presence
... more devices here
```

Hopefully that brings your config in.

**Comment by Tony763** [comment]
```
2024-02-04 00:22:16.883 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration virtual which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-02-04 00:22:19.455 WARNING (MainThread) [asyncio] Executing <Task pending name='Task-195' coro=<RequestHandler._handle_request() running at /srv/ha/venv/lib/python3.11/site-packages/aiohttp/web_protocol.py:452> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/lib/python3.11/asyncio/base_events.py:427> cb=[Task.task_wakeup()] created at /srv/ha/venv/lib/python3.11/site-packages/aiohttp/web_protocol.py:527> took 0.670 seconds
2024-02-04 00:22:19.941 WARNING (MainThread) [homeassistant.components.debugpy] Listening for remote debug connection on 0.0.0.0:5680
2024-02-04 00:22:20.482 WARNING (MainThread) [asyncio] Executing <Task pending name='setup component bluetooth' coro=<_async_setup_component() running at /srv/ha/venv/lib/python3.11/site-packages/homeassistant/setup.py:332> wait_for=<Task pending name='Storage load bluetooth.passive_update_processor' coro=<Store._async_load() running at /srv/ha/venv/lib/python3.11/site-packages/homeassistant/helpers/storage.py:135> cb=[set.remove(), Task.task_wakeup()] created at /srv/ha/venv/lib/python3.11/site-packages/homeassistant/core.py:624> cb=[set.remove(), Task.task_wakeup()] created at /srv/ha/venv/lib/python3.11/site-packages/homeassistant/core.py:624> took 0.135 seconds
2024-02-04 00:22:23.772 WARNING (MainThread) [asyncio] Executing <Task pending name='setup component cloud' coro=<_async_setup_component() running at /srv/ha/venv/lib/python3.11/site-packages/homeassistant/setup.py:332> wait_for=<Task pending name='Storage load cloud' coro=<Store._async_load() running at /srv/ha/venv/lib/python3.11/site-packages/homeassistant/helpers/storage.py:135> cb=[set.remove(), Task.task_wakeup()] created at /srv/ha/venv/lib/python3.11/site-packages/homeassistant/core.py:624> cb=[set.remove(), Task.task_wakeup()] created at /srv/ha/venv/lib/python3.11/site-packages/homeassistant/core.py:624> took 3.140 seconds
2024-02-04 00:22:24.265 WARNING (MainThread) [asyncio] Executing <Task pending name='setup component binary_sensor' coro=<_async_setup_component() running at /srv/ha/venv/lib/python3.11/site-packages/homeassistant/setup.py:365> cb=[set.remove(), Task.task_wakeup()] created at /srv/ha/venv/lib/python3.11/site-packages/homeassistant/core.py:624> took 0.328 seconds
2024-02-04 00:22:24.682 WARNING (MainThread) [asyncio] Executing <Task pending name='setup component default_config' coro=<_async_setup_component() running at /srv/ha/venv/lib/python3.11/site-packages/homeassistant/setup.py:243> wait_for=<_GatheringFuture pending cb=[Task.task_wakeup()] created at /usr/lib/python3.11/asyncio/tasks.py:699> cb=[set.remove(), Task.task_wakeup()] created at /srv/ha/venv/lib/python3.11/site-packages/homeassistant/core.py:624> took 0.325 seconds
2024-02-04 00:22:25.359 WARNING (MainThread) [asyncio] Executing <Task pending name='setup component stream' coro=<_async_setup_component() running at /srv/ha/venv/lib/python3.11/site-packages/homeassistant/setup.py:365> cb=[set.remove(), <1 more>, Task.task_wakeup()] created at /srv/ha/venv/lib/python3.11/site-packages/homeassistant/core.py:624> took 0.113 seconds
2024-02-04 00:22:25.518 WARNING (MainThread) [asyncio] Executing <Task pending name='setup component panasonic_viera' coro=<_async_setup_component() running at /srv/ha/venv/lib/python3.11/site-packages/homeassistant/setup.py:365> cb=[set.remove(), Task.task_wakeup()] created at /srv/ha/venv/lib/python3.11/site-packages/homeassistant/core.py:624> took 0.158 seconds
2024-02-04 00:22:25.578 ERROR (MainThread) [homeassistant.components.switch] The virtual platform for the switch integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:25.580 ERROR (MainThread) [homeassistant.components.switch] The virtual platform for the switch integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:25.581 ERROR (MainThread) [homeassistant.components.switch] The virtual platform for the switch integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:25.581 ERROR (MainThread) [homeassistant.components.switch] The virtual platform for the switch integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:25.582 ERROR (MainThread) [homeassistant.components.switch] The virtual platform for the switch integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:25.582 ERROR (MainThread) [homeassistant.components.switch] The virtual platform for the switch integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:26.238 WARNING (MainThread) [asyncio] Executing <Task pending name='setup component sensor' coro=<_async_setup_component() running at /srv/ha/venv/lib/python3.11/site-packages/homeassistant/setup.py:365> cb=[set.remove(), <5 more>, Task.task_wakeup()] created at /srv/ha/venv/lib/python3.11/site-packages/homeassistant/core.py:624> took 0.153 seconds
2024-02-04 00:22:26.288 ERROR (MainThread) [homeassistant.components.sensor] The virtual platform for the sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:26.289 ERROR (MainThread) [homeassistant.components.sensor] The virtual platform for the sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:26.290 ERROR (MainThread) [homeassistant.components.sensor] The virtual platform for the sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:26.290 ERROR (MainThread) [homeassistant.components.sensor] The virtual platform for the sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:26.291 ERROR (MainThread) [homeassistant.components.sensor] The virtual platform for the sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:26.291 ERROR (MainThread) [homeassistant.components.sensor] The virtual platform for the sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:26.292 ERROR (MainThread) [homeassistant.components.sensor] The virtual platform for the sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:26.292 ERROR (MainThread) [homeassistant.components.sensor] The virtual platform for the sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:26.293 ERROR (MainThread) [homeassistant.components.sensor] The virtual platform for the sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:26.293 ERROR (MainThread) [homeassistant.components.sensor] The virtual platform for the sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:26.294 ERROR (MainThread) [homeassistant.components.sensor] The virtual platform for the sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:26.295 ERROR (MainThread) [homeassistant.components.sensor] The virtual platform for the sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:26.295 ERROR (MainThread) [homeassistant.components.sensor] The virtual platform for the sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:26.296 ERROR (MainThread) [homeassistant.components.sensor] The virtual platform for the sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:26.296 ERROR (MainThread) [homeassistant.components.sensor] The virtual platform for the sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:26.297 ERROR (MainThread) [homeassistant.components.sensor] The virtual platform for the sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:26.297 ERROR (MainThread) [homeassistant.components.sensor] The virtual platform for the sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:26.298 ERROR (MainThread) [homeassistant.components.sensor] The virtual platform for the sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:26.298 ERROR (MainThread) [homeassistant.components.sensor] The virtual platform for the sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:26.299 ERROR (MainThread) [homeassistant.components.sensor] The virtual platform for the sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:26.299 ERROR (MainThread) [homeassistant.components.sensor] The virtual platform for the sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:26.300 ERROR (MainThread) [homeassistant.components.sensor] The virtual platform for the sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:26.300 ERROR (MainThread) [homeassistant.components.sensor] The virtual platform for the sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:26.301 ERROR (MainThread) [homeassistant.components.sensor] The virtual platform for the sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:26.302 ERROR (MainThread) [homeassistant.components.sensor] The virtual platform for the sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:26.302 ERROR (MainThread) [homeassistant.components.sensor] The virtual platform for the sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:26.303 ERROR (MainThread) [homeassistant.components.sensor] The virtual platform for the sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:26.303 ERROR (MainThread) [homeassistant.components.sensor] The virtual platform for the sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:26.304 ERROR (MainThread) [homeassistant.components.sensor] The virtual platform for the sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:26.304 ERROR (MainThread) [homeassistant.components.sensor] The virtual platform for the sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:26.305 ERROR (MainThread) [homeassistant.components.sensor] The virtual platform for the sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:26.305 ERROR (MainThread) [homeassistant.components.sensor] The virtual platform for the sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:26.306 ERROR (MainThread) [homeassistant.components.sensor] The virtual platform for the sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:26.307 ERROR (MainThread) [homeassistant.components.sensor] The virtual platform for the sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:26.308 ERROR (MainThread) [homeassistant.components.sensor] The virtual platform for the sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:26.308 ERROR (MainThread) [homeassistant.components.sensor] The virtual platform for the sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:26.309 ERROR (MainThread) [homeassistant.components.sensor] The virtual platform for the sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:26.856 WARNING (MainThread) [asyncio] Executing <Task pending name='setup component mobile_app' coro=<_async_setup_component() running at /srv/ha/venv/lib/python3.11/site-packages/homeassistant/setup.py:332> wait_for=<Task pending name='Storage load mobile_app' coro=<Store._async_load() running at /srv/ha/venv/lib/python3.11/site-packages/homeassistant/helpers/storage.py:135> cb=[set.remove(), Task.task_wakeup()] created at /srv/ha/venv/lib/python3.11/site-packages/homeassistant/core.py:624> cb=[set.remove(), <1 more>, Task.task_wakeup()] created at /srv/ha/venv/lib/python3.11/site-packages/homeassistant/core.py:624> took 0.468 seconds
2024-02-04 00:22:27.072 WARNING (MainThread) [asyncio] Executing <Task pending name='config entry setup Home met c5687bcdbd9da8f195d3914e423ebbd7' coro=<ConfigEntry.async_setup() running at /srv/ha/venv/lib/python3.11/site-packages/homeassistant/config_entries.py:406> wait_for=<_GatheringFuture pending cb=[Task.task_wakeup()] created at /usr/lib/python3.11/asyncio/tasks.py:699> cb=[gather.<locals>._done_callback() at /usr/lib/python3.11/asyncio/tasks.py:754] created at /usr/lib/python3.11/asyncio/tasks.py:374> took 0.107 seconds
2024-02-04 00:22:27.522 WARNING (MainThread) [asyncio] Executing <Task pending name='Task-805' coro=<async_setup_platform() running at /srv/ha/venv/lib/python3.11/site-packages/homeassistant/components/snmp/sensor.py:163> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/lib/python3.11/asyncio/base_events.py:427> cb=[shield.<locals>._inner_done_callback() at /usr/lib/python3.11/asyncio/tasks.py:881] created at /usr/lib/python3.11/asyncio/tasks.py:670> took 0.219 seconds
2024-02-04 00:22:27.614 ERROR (MainThread) [homeassistant.components.binary_sensor] The virtual platform for the binary_sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:27.617 ERROR (MainThread) [homeassistant.components.binary_sensor] The virtual platform for the binary_sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:27.617 ERROR (MainThread) [homeassistant.components.binary_sensor] The virtual platform for the binary_sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:27.618 ERROR (MainThread) [homeassistant.components.binary_sensor] The virtual platform for the binary_sensor integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:27.618 ERROR (MainThread) [homeassistant.components.light] The virtual platform for the light integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:27.619 ERROR (MainThread) [homeassistant.components.light] The virtual platform for the light integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:27.620 ERROR (MainThread) [homeassistant.components.light] The virtual platform for the light integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:27.620 ERROR (MainThread) [homeassistant.components.light] The virtual platform for the light integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:27.621 ERROR (MainThread) [homeassistant.components.light] The virtual platform for the light integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:27.621 ERROR (MainThread) [homeassistant.components.light] The virtual platform for the light integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:27.622 ERROR (MainThread) [homeassistant.components.light] The virtual platform for the light integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:27.622 ERROR (MainThread) [homeassistant.components.light] The virtual platform for the light integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:27.623 ERROR (MainThread) [homeassistant.components.light] The virtual platform for the light integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:27.623 ERROR (MainThread) [homeassistant.components.light] The virtual platform for the light integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:27.624 ERROR (MainThread) [homeassistant.components.light] The virtual platform for the light integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:27.624 ERROR (MainThread) [homeassistant.components.light] The virtual platform for the light integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:27.625 ERROR (MainThread) [homeassistant.components.light] The virtual platform for the light integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:27.625 ERROR (MainThread) [homeassistant.components.light] The virtual platform for the light integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:27.626 ERROR (MainThread) [homeassistant.components.light] The virtual platform for the light integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:27.626 ERROR (MainThread) [homeassistant.components.light] The virtual platform for the light integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:27.627 ERROR (MainThread) [homeassistant.components.light] The virtual platform for the light integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:27.627 ERROR (MainThread) [homeassistant.components.light] The virtual platform for the light integration does not support platform setup. Please remove it from your config.
2024-02-04 00:22:28.663 ERROR (MainThread) [homeassistant.components.panasonic_viera.config_flow] Could not establish remote connection: <urlopen error [Errno 113] No route to host>
2024-02-04 00:22:35.655 WARNING (MainThread) [asyncio] Executing <Task finished name='config entry flow octoprint e185de19391e80e85384c4bcb07c1213' coro=<ConfigEntriesFlowManager._async_init() done, defined at /srv/ha/venv/lib/python3.11/site-packages/homeassistant/config_entries.py:898> result=(<homeassistan... 0x7f49d55890>, {'data_schema': <Schema({'use... 0x7f410beb90>, 'description_placeholders': None, 'errors': None, 'flow_id': 'e185de19391e...4c4bcb07c1213', ...}) created at /usr/lib/python3.11/asyncio/tasks.py:374> took 0.363 seconds
2024-02-04 00:22:37.928 WARNING (MainThread) [asyncio] Executing <TimerHandle when=4069647.66275281 _run_async_call_action(<HomeAssistant RUNNING>, <Job EntityPl...0x7f4a3b9800>>) at /srv/ha/venv/lib/python3.11/site-packages/homeassistant/helpers/event.py:1450 created at /srv/ha/venv/lib/python3.11/site-packages/homeassistant/helpers/event.py:1497> took 0.122 seconds
2024-02-04 00:22:43.493 WARNING (MainThread) [asyncio] Executing <Task pending name='Task-195' coro=<RequestHandler._handle_request() running at /srv/ha/venv/lib/python3.11/site-packages/aiohttp/web_protocol.py:452> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/lib/python3.11/asyncio/base_events.py:427> cb=[Task.task_wakeup()] created at /srv/ha/venv/lib/python3.11/site-packages/aiohttp/web_protocol.py:527> took 0.117 seconds
```

**Comment by Tony763** [comment]
Found it:
```
2024-02-04 00:28:36.515 DEBUG (MainThread) [custom_components.virtual.cfg] couldn't save user data [Errno 2] No such file or directory: '/config/virtual.yaml'
2024-02-04 00:28:36.516 DEBUG (MainThread) [custom_components.virtual.cfg] no meta data yet [Errno 2] No such file or directory: '/config/.storage/virtual.meta.json'
```
These two should be `ERROR` not DEBUG :slightly_smiling_face: 

Configuration try to write to nonexist directory `/config` as my HA configuration is inside `/home/homeassistant/.homeassistant/` directory.

**Comment by Tony763** [comment]
I see, thy are hardcoded:
```
IMPORTED_YAML_FILE = "/config/virtual.yaml"
META_JSON_FILE = "/config/.storage/virtual.meta.json"
```

**Comment by Tony763** [comment]
To get actual config path, You could use `hass.config.path())` function in `setup`:


```
async def async_setup(......
    _LOGGER.error(hass.config.path())
    _LOGGER.error(hass.config.path(".storage"))
```
Returns:

```
![image](https://github.com/twrecked/hass-virtual/assets/5598750/b8b94044-55d4-4d8e-a42a-2a80b3fd3cb9)

**Comment by twrecked** [comment]
I was just going to say this was down to my naivety!

I'll update them later this evening.

**Comment by twrecked** [comment]
Sorry this is a bit of pain but can you try again?

I've tested this on my set up but I just have everything under `/config`.

**Comment by Tony763** [comment]
No problem, last change works.  `virtual.yaml` was created and everything was importet. Thank You

![image](https://github.com/twrecked/hass-virtual/assets/5598750/51e42066-cd2d-4143-8daf-fc7e0d20a258)
