### ISSUE TITLE
0.9.x - Set available

### ISSUE THREAD

**Issue by Tony763** [twrecked/hass-virtual#97]
Hi @twrecked, I am unable to set availability of entity trough websocket. This worked in 0.6.x.

```
2024-02-04 17:42:08.895 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [546918702784] l component not set up
Traceback (most recent call last):
File "/srv/ha/venv/lib/python3.11/site-packages/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
response = await hass.services.async_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/ha/venv/lib/python3.11/site-packages/homeassistant/core.py", line 2149, in async_call
response_data = await coro
^^^^^^^^^^
File "/srv/ha/venv/lib/python3.11/site-packages/homeassistant/core.py", line 2186, in _execute_service
return await target(service_call)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/ha/venv/lib/python3.11/site-packages/homeassistant/helpers/service.py", line 1043, in check_permissions
return await service_handler(call)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/homeassistant/.homeassistant/custom_components/virtual/__init__.py", line 142, in async_virtual_service_set_available
await async_virtual_set_availability_service(hass, call)
File "/home/homeassistant/.homeassistant/custom_components/virtual/__init__.py", line 206, in async_virtual_set_availability_service
get_entity_from_domain(hass, domain, entity_id).set_available(value)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/homeassistant/.homeassistant/custom_components/virtual/__init__.py", line 187, in get_entity_from_domain
raise HomeAssistantError("{} component not set up".format(domain))
homeassistant.exceptions.HomeAssistantError: l component not set up
2024-02-04 17:42:08.918 INFO (MainThread) [custom_components.virtual] set_available service called
2024-02-04 17:42:08.918 INFO (MainThread) [custom_components.virtual] s set_avilable(value=False)
2024-02-04 17:42:08.918 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [546918702784] s component not set up
Traceback (most recent call last):
File "/srv/ha/venv/lib/python3.11/site-packages/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
response = await hass.services.async_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/ha/venv/lib/python3.11/site-packages/homeassistant/core.py", line 2149, in async_call
response_data = await coro
^^^^^^^^^^
File "/srv/ha/venv/lib/python3.11/site-packages/homeassistant/core.py", line 2186, in _execute_service
return await target(service_call)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/ha/venv/lib/python3.11/site-packages/homeassistant/helpers/service.py", line 1043, in check_permissions
return await service_handler(call)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/homeassistant/.homeassistant/custom_components/virtual/__init__.py", line 142, in async_virtual_service_set_available
await async_virtual_set_availability_service(hass, call)
File "/home/homeassistant/.homeassistant/custom_components/virtual/__init__.py", line 206, in async_virtual_set_availability_service
get_entity_from_domain(hass, domain, entity_id).set_available(value)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/homeassistant/.homeassistant/custom_components/virtual/__init__.py", line 187, in get_entity_from_domain
raise HomeAssistantError("{} component not set up".format(domain))
homeassistant.exceptions.HomeAssistantError: s component not set up
```

![image](https://github.com/twrecked/hass-virtual/assets/5598750/b4b9cfe3-6220-4c59-b771-15cb8f171372)

Example websocket payload:
```
snd = {
  "id": id_msg,
  "type": "call_service",
  "domain": "virtual",
  "service": "set_available",
  "service_data": {
  "entity_id": id_,
  "value": event["state"]
  }
}
```

**Comment by Tony763** [comment]
Syntax for `set_available` changed:

This works:
```
 snd = {
  "id": id_msg,
  "type": "call_service",
  "domain": "virtual",
  "service": "set_available",
  "service_data": {
  "value": event["state"]
  },
  "target": {
      "entity_id": id_
  }
}
```

**Comment by Tony763** [comment]
This error occur not just with websocket, I can simulate it inside `Developer tools > Services`

Firing empty service shows request to define `entity_id`, `device_id` or `area_id` in `target` or `data`.
![image](https://github.com/twrecked/hass-virtual/assets/5598750/3bb38664-cd3c-4ed4-8dad-67447cdb824f)

Adding `entity _id` inside `target` works as expected:
![image](https://github.com/twrecked/hass-virtual/assets/5598750/9eb79ef0-6624-4de0-ac66-9b94375c68de)

But adding `entity _id` inside  `data` as suggested by HA fail with error from above:
![image](https://github.com/twrecked/hass-virtual/assets/5598750/7a3fb391-6f9e-4c59-92c2-c53e3c77f203)
(`b` is probably first letter from `binary_sensor.aqua_bdoor`)

**Comment by twrecked** [comment]
I had to change some stuff around to make the UI Mode work. I'll take another look.

**Comment by twrecked** [comment]
I'll fix it. I need to check if entity_id is a list or not.

**Comment by Tony763** [comment]
Yes, this works. Thank You :slightly_smiling_face:
